### ISSUE TITLE
How to use STANDARD RASPBIAN OS

### ISSUE THREAD

**Issue by nduongn** [Avnet/raspberrypi-industrial-gateway#1]
Hi all,

In the datasheet, under STANDARD RASPBIAN stated "Standard Raspbian can be used". Does anyone know how to use Raspbian in this gateway? Thanks.

**Comment by gnulux** [comment]
Hi , 

I think you have to open the gateway and copy the image with rpiboot. 
I'm going to try this. 
Keep you in touch

**Comment by ferrim** [comment]
Interesting, keep us informed!

**Comment by gnulux** [comment]
Hi ,

I come back to you with what i did on my smartedge IIOT gateway. 
In fact i succeed to start Raspbian Buster lite on this box but before that,  i have to open it and connect my desktop on usb type A connector on the board.As I said previously, you must use rpiboot tool in order to mount the 2 partitions on your desktop.Then you copy/backup file from there.
You can not boot Buster image or any Rasbian image before copying kernel7.img , bcm2710-rpi-custom.dtb and dt-blob.bin.kernel7 file in official install seems to be an u-boot binary . I never succeeded in booting without this file. 
To go further, I tried to compile the latest Raspbian git kernel with Avnet dtd custom files. It boots correctly too (still with kernel7.img from the official image)  but a few minutes later I lost my keyboard and had issues with bluetooth. 
I don't give up for Buster release but my next step will be to test Stretch release and see if it is more stable.I am also interested in implementing Secure-Boot with these releases.

**Comment by ferrim** [comment]
Thank you gnulux,
it seems like a good step forward!
I am waiting  the delivery of my first SmartEdge but the fact that Farnell do not have stock until the end of July is a big problem for a single-source product like this.
Please keep us updated, thanks.

**Comment by ccooll** [comment]
I hope you had some success and that you can share back your story on how you managed it.  

I have been wanting to install buster on mine, but after reading your comment, I decided against it hoping you would tell if you manage to make it work. 

Good luck and thanks for sharing

**Comment by WaynePetersIot** [comment]
Make a copy of your image.
Put Raspbian of choice on gateway, stay away from Buster Full as you will not have disk space left
copy /boot contents from original image to gateway
copy /rootfs/lib/modules contents from original image to gateway
