### ISSUE TITLE
gateway does not boot after upgrade

### ISSUE THREAD

**Issue by edgale** [Avnet/raspberrypi-industrial-gateway#3]
I built the current image and flashed it to the gateway. Was successful and could run a few things I wanted to test.
Then I wanted to ```apt-get update``` and ```apt-get upgrade```. This was also successful. But after restarting the gateway it was not booting anymore.
I can still mount the storage and flash the image again. But can not update the gateway.
Is there a fix for this? 
Thanks for your help.

**Comment by wsradcliffe** [comment]
This is a known issue and has to do with the fact that standard Raspberry Pi images will not run on this Gateway.  Here is description and workaround from the User Guide (available here: [www.element14.com/gateway](url))

WARNING: Because of the above differences, performing any standard Raspberry Pi update that modifies the kernel or boot files will likely prevent the system from booting.  This includes writing a standard Raspbian image to the Gateway or performing "apt-get upgrade".  If this happens, you will have to follow the image update instructions located elsewhere in this guide (Section 3.5) to fix the /boot files or re-image the system.  To prevent Raspbian updates from automatically updating your kernel and firmware files (and bricking your Gateway), execute the following commands:
```
sudo apt-mark hold raspberrypi-bootloader
sudo apt-mark hold raspberrypi-kernel
sudo apt-mark hold raspberrypi-sys-mods
```

**Comment by edgale** [comment]
Thank you very much for your quick respond. I did not see this part in the user guide. I will try that. It would just be frustrating to someday forget about this and updating the gateway and then having it bricked ;)
