### ISSUE TITLE
gpio not working for me

### ISSUE THREAD

**Issue by edgale** [Avnet/raspberrypi-industrial-gateway#4]
Hey there,

I setup a new gateway with the latest image from this repo.
I tried to access the gpio's like descripted in User Guide.
I did:
```bash
echo 201 > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio201/direction
echo 1 > /sys/class/gpio/gpio201/value
```
As I understand it this sould now make output, output a signal.
But I can't meassure anything on any output with my voltmeter.

Plus the schematic's say that the gpio numbers are differnt.
![image](https://user-images.githubusercontent.com/4374065/85842464-0719c080-b7a0-11ea-8f8a-bcf712837c00.png)

Am I making some mistake?
I also tried all other 200 numbers described in the user guide plus the output numbers from the schematic.

Thank you for your help.

**Comment by wsradcliffe** [comment]
Hi Maximilian,

The GPIO outputs are open-drain.  They can only drive an otherwise high level signal to a low level.  An external pull-up can be used to set the high level.  The pull-up voltage must be 5V or greater, then should size the resistor.  If 24V, a resistor value of 5K-10K can be used.  Also note that the GPIO GND is isolated and needs connected to the pull-up voltage's GND reference.

**Comment by edgale** [comment]
Thank you very much for that. Worked like a charm.
